spring.application.name=RateLimitingAPIGateway

spring.datasource.url=jdbc:postgresql://localhost:5432/rate_limiting_gateway
spring.datasource.username=mac
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
